server:
  port: 8086
spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/userauthenticationdb}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:admin}
    driver-class-name: ${MYSQL_DRIVER:com.mysql.cj.jdbc.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: user-authentication-service


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    registerWithEureka: true

